spring.application.name: payment
server.port: ${SERVER_PORT:8082}
spring.kafka:
  bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:broker:9092}
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

spring.datasource:
  url: jdbc:h2:mem:paymentdb
  driver-class-name: org.h2.Driver
  username: sa
  password: 
spring.h2.console:
  enabled: true
  path: /h2-console
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: create-drop
  show-sql: true

spring.output.ansi.enabled: ALWAYS

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always